---

- name: Add HAProxy config for ScaleIO Gateway
  hosts: haproxy
  gather_facts: true
  user: root
  roles:
  - { role: "haproxy-config" }
  vars_files:
  - "/opt/openstack-ansible/playbooks/vars/configs/haproxy_config.yml"
  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
