---

- name: Upload package wrapper
  template: dest="/var/tmp/package_wrapper.sh" src="templates/package_wrapper.sh.j2" mode="0775" owner="root" group="root" force="yes"

- name: copy deb file
  copy: src="{{ item }}" dest="/var/tmp" mode="0644"
  with_fileglob:
    - "{{ scaleio_install_file_location }}/*{{ file_glob_name }}*.deb"

- name: list the deb file
  register: package_file
  find: paths="/var/tmp/" patterns="*{{ file_glob_name }}*.deb"
