---

- name: Upload package wrapper
  template: dest="/var/tmp/package_wrapper.sh" src="templates/package_wrapper.sh.j2" mode="0775" owner="root" group="root" force="yes"

- name: Copy deb file
  copy: src="{{ item }}" dest="/var/tmp" mode="0644"
  with_fileglob:
    - "{{ scaleio_install_file_location }}/*{{ file_glob_name }}*.deb"

- name: List the deb file
  register: package_file
  find: paths="/var/tmp/" patterns="*{{ file_glob_name }}*.deb"

- name: Install ScaleIO Gateway package
  raw: "/var/tmp/package_wrapper.sh dpkg -i {{ package_file.files[0].path }}"

#- name: Wait for Tomcat to start
#  wait_for: port=443

- name: Adding Tomcat jvmRoute ID
  lineinfile: dest=/opt/emc/scaleio/gateway/conf/server.xml regexp="^''<Engine name="Catalina" defaultHost="localhost">''" line="<Engine name="Catalina" defaultHost="localhost" jvmRoute="{{ ansible_hostname }}">"
