---

- name: Upload package wrapper
  template: dest="/var/tmp/package_wrapper.sh" src="templates/package_wrapper.sh.j2" mode="0775" owner="root" group="root" force="yes"

- name: Copy deb file
  copy: src="{{ item }}" dest="/var/tmp" mode="0644"
  with_fileglob:
    - "{{ scaleio_install_file_location }}/*{{ file_glob_name }}*.deb"

- name: List the deb file
  register: package_file
  find: paths="/var/tmp/" patterns="*{{ file_glob_name }}*.deb"

- name: Check if package is installed
  command: dpkg-query -l emc-scaleio-gateway
  register: deb_check

- name: Install ScaleIO Gateway package
  raw: "/var/tmp/package_wrapper.sh dpkg -i {{ package_file.files[0].path }}"
  #comment when need force reinstall or set new GATEWAY_ADMIN_PASSWORD
  #when: deb_check.stdout.find('no packages found') != -1

- name: Wait for Tomcat to start
  wait_for: port=80 delay=10
  when: deb_check.stdout.find('no packages found') != -1

- name: Change default Tomcat HTTPS port from 443 to 9943
  replace: dest={{ scaleio_catalina_properties_file }} regexp='^.*ssl.port=.*' replace="ssl.port=9943"
  notify:
  - Restart ScaleIO Gateway

- name: Adding Tomcat jvmRoute ID
  replace: dest={{ scaleio_tomcat_properties_file }} regexp='^.*<Engine name="Catalina" defaultHost="localhost".*' replace="<Engine name="Catalina" defaultHost="localhost" jvmRoute="{{ ansible_hostname }}">"
  notify:
  - Restart ScaleIO Gateway

- name: Adding MDM IP addresses
  replace: dest={{ scaleio_gateway_user_properties_file }} regexp='^.*mdm.ip.addresses=.*' replace="mdm.ip.addresses={{ scaleio_mdm1_ip }};{{ scaleio_mdm2_ip }}"
  notify:
  - Restart ScaleIO Gateway

- name: Remove package wrapper
  file: path="/var/tmp/package_wrapper.sh" state=absent
